### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by lovromazgon**
This PR adds more info in the readme and proto file.

### CODE REVIEW

**Comment by anaptfox** [comment]
Great job 🧡

It looks like this has the instructions to generate the scaffold, but what about the next steps? 

Then it would allow you to structure the README around those concepts:

1. Generate
2. Build?
3. Add to Conduit

For example, what would the `POST /v1/connectors` call be?

**Comment by ahmeroxa** [comment]
I think this is good, but I would make the callout to use [Connector Plugin SDK](https://github.com/ConduitIO/connector-plugin-sdk) much more prominent at the top.

We want people to essentially ignore this repo and go there instead, so the first sentence should be "if you're trying to write a connector, use the SDK..."

**Comment by lovromazgon** [comment]
Thanks for the feedback @anaptfox, @ahmeroxa! Let me know how you like the changes in my last commit.

**Comment by lovromazgon** [comment]
@anaptfox @ahmeroxa I assume you are happy with this and we can merge?

**Pull request merged**
